#!/bin/bash

SNAPSHOTS_DIR=${BACKUP_ROOT}/SNAPSHOT

YEAR=`date +%Y`
DATE=`date +%m%d`

SNAP_DIR=${SNAPSHOTS_DIR}/${YEAR}/${DATE}
LOG_BASE_DIR=${BACKUP_ROOT}/LOG
LOG_DIR=${LOG_BASE_DIR}/${YEAR}
LOG_FILE=${LOG_DIR}/${DATE}.log
RSYNC_EXCLUDE_FILE=${BACKUP_ROOT}/exclude.ptn
